-- V1__init.sql — PostgreSQL 16 (esquema requerimientos.txt §5.1)

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    programa_academico VARCHAR(120) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    conectado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_ultima_conexion TIMESTAMP,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_usuario_estado ON usuarios (estado);
CREATE INDEX idx_usuario_conectado ON usuarios (conectado);

CREATE TABLE sesiones_activas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    ip VARCHAR(45) NOT NULL,
    inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_actividad TIMESTAMP,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    aplicacion VARCHAR(50),
    version_app VARCHAR(30)
);

CREATE INDEX idx_sesion_usuario ON sesiones_activas (usuario_id);
CREATE INDEX idx_sesion_activa ON sesiones_activas (activa);

CREATE TABLE conexiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    direccion_ip VARCHAR(45) NOT NULL,
    hora_conexion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hora_desconexion TIMESTAMP,
    mensajes_sesion INT NOT NULL DEFAULT 0,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_operativo VARCHAR(120),
    dispositivo VARCHAR(120),
    sesion_id BIGINT REFERENCES sesiones_activas(id) ON DELETE SET NULL
);

CREATE INDEX idx_conexion_usuario ON conexiones (usuario_id);
CREATE INDEX idx_conexion_activa ON conexiones (activa);

CREATE TABLE archivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ruta VARCHAR(767) NOT NULL UNIQUE,
    tamano BIGINT NOT NULL DEFAULT 0,
    tipo VARCHAR(30) NOT NULL,
    mime VARCHAR(255),
    hash_sha256 CHAR(64) NOT NULL,
    propietario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_archivo_propietario ON archivos (propietario_id);
CREATE INDEX idx_archivo_hash ON archivos (hash_sha256);

CREATE TABLE mensajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    destinatario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL,
    contenido TEXT,
    hash_sha256 CHAR(64),
    num_caracteres INT,
    num_palabras INT,
    etapas_filtrado TEXT,
    fecha_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_remitente VARCHAR(45),
    ip_destinatario VARCHAR(45),
    archivo_id BIGINT REFERENCES archivos(id) ON DELETE SET NULL
);

CREATE INDEX idx_mensaje_conv ON mensajes (remitente_id, destinatario_id, fecha_envio);
CREATE INDEX idx_mensaje_dest ON mensajes (destinatario_id);

CREATE TABLE registro_acciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    descripcion TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(45),
    detalles TEXT
);

CREATE INDEX idx_accion_tipo ON registro_acciones (tipo);
CREATE INDEX idx_accion_fecha ON registro_acciones (fecha);

CREATE TABLE configuracion_limites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_conexiones_usuario INT NOT NULL DEFAULT 3,
    max_conexiones_totales INT NOT NULL DEFAULT 100,
    max_archivos_usuario INT NOT NULL DEFAULT 100,
    max_tamano_archivo BIGINT NOT NULL DEFAULT 10485760,
    max_archivos_dia INT NOT NULL DEFAULT 20,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_config_activa ON configuracion_limites (activa);

INSERT INTO configuracion_limites (activa) VALUES (TRUE);
