-- V1__init.sql — Oracle 23 FREE (esquema requerimientos.txt §5.1)

CREATE TABLE usuarios (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(120) NOT NULL,
    programa_academico VARCHAR2(120) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    conectado NUMBER(1) DEFAULT 0 NOT NULL,
    fecha_ultima_conexion TIMESTAMP,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT uk_usuarios_codigo UNIQUE (codigo)
);

CREATE INDEX idx_usuario_estado ON usuarios (estado);
CREATE INDEX idx_usuario_conectado ON usuarios (conectado);

CREATE TABLE sesiones_activas (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER(19) NOT NULL,
    token VARCHAR2(255) NOT NULL,
    ip VARCHAR2(45) NOT NULL,
    inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ultima_actividad TIMESTAMP,
    activa NUMBER(1) DEFAULT 1 NOT NULL,
    aplicacion VARCHAR2(50),
    version_app VARCHAR2(30),
    CONSTRAINT uk_sesion_token UNIQUE (token),
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE INDEX idx_sesion_usuario ON sesiones_activas (usuario_id);

CREATE TABLE conexiones (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER(19) NOT NULL,
    direccion_ip VARCHAR2(45) NOT NULL,
    hora_conexion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    hora_desconexion TIMESTAMP,
    mensajes_sesion NUMBER(10) DEFAULT 0 NOT NULL,
    activa NUMBER(1) DEFAULT 1 NOT NULL,
    sistema_operativo VARCHAR2(120),
    dispositivo VARCHAR2(120),
    sesion_id NUMBER(19),
    CONSTRAINT fk_conexion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_conexion_sesion FOREIGN KEY (sesion_id) REFERENCES sesiones_activas(id) ON DELETE SET NULL
);

CREATE INDEX idx_conexion_usuario ON conexiones (usuario_id);

CREATE TABLE archivos (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    ruta VARCHAR2(767) NOT NULL,
    tamano NUMBER(19) DEFAULT 0 NOT NULL,
    tipo VARCHAR2(30) NOT NULL,
    mime VARCHAR2(255),
    hash_sha256 CHAR(64) NOT NULL,
    propietario_id NUMBER(19) NOT NULL,
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_archivos_ruta UNIQUE (ruta),
    CONSTRAINT fk_archivo_usuario FOREIGN KEY (propietario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE INDEX idx_archivo_hash ON archivos (hash_sha256);

CREATE TABLE mensajes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id NUMBER(19) NOT NULL,
    destinatario_id NUMBER(19) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    contenido CLOB,
    hash_sha256 CHAR(64),
    num_caracteres NUMBER(10),
    num_palabras NUMBER(10),
    etapas_filtrado CLOB,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_remitente VARCHAR2(45),
    ip_destinatario VARCHAR2(45),
    archivo_id NUMBER(19),
    CONSTRAINT fk_msg_remitente FOREIGN KEY (remitente_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_msg_destinatario FOREIGN KEY (destinatario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_msg_archivo FOREIGN KEY (archivo_id) REFERENCES archivos(id) ON DELETE SET NULL
);

CREATE INDEX idx_mensaje_conv ON mensajes (remitente_id, destinatario_id, fecha_envio);

CREATE TABLE registro_acciones (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(30) NOT NULL,
    usuario_id NUMBER(19),
    descripcion CLOB NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip VARCHAR2(45),
    detalles CLOB,
    CONSTRAINT fk_accion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE INDEX idx_accion_fecha ON registro_acciones (fecha);

CREATE TABLE configuracion_limites (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_conexiones_usuario NUMBER(10) DEFAULT 3 NOT NULL,
    max_conexiones_totales NUMBER(10) DEFAULT 100 NOT NULL,
    max_archivos_usuario NUMBER(10) DEFAULT 100 NOT NULL,
    max_tamano_archivo NUMBER(19) DEFAULT 10485760 NOT NULL,
    max_archivos_dia NUMBER(10) DEFAULT 20 NOT NULL,
    activa NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_config_activa ON configuracion_limites (activa);

INSERT INTO configuracion_limites (activa) VALUES (1);
